### ISSUE TITLE
Can you also add base images for openjdk 10 and openjdk 11

### ISSUE THREAD

**Issue by wavermartijn** [Transmode/gradle-docker#148] opened 2018-10-15 13:38 UTC
https://github.com/Transmode/gradle-docker/blob/3d22f0904058a3530ff3eda31ea54f78377ec01e/src/main/java/se/transmode/gradle/plugins/docker/JavaBaseImage.java#L27

**Comment by wavermartijn** [comment] 2018-10-15 13:47
Sorry, I saw you have a commit for the most recent versions already. Hope they will be merged soon

**Comment by jomach** [comment] 2018-12-21 11:17
shouldn't this work: 
docker {
    baseImage = 'openjdk:11-jre-slim'
 ...
}

It fails on my because of 
Caused by: java.lang.IllegalArgumentException: No Java base image for the supplied target 11 found.

**Comment by bjornmagnusson** [comment] 2019-01-27 20:01
Fixed by #145

**Closed by bjornmagnusson** 2019-01-27 20:01 UTC
